### ISSUE TITLE
Tldr Pages: [Suggestion] use man"

### ISSUE THREAD

**Issue by githubtefo** [duckduckgo/zeroclickinfo-fathead#893] opened 2017-11-29 22:09 UTC
------
IA Page:  http://duck.co/ia/view/tldr_pages 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555

**Comment by mattr555** [comment] 2017-11-30 01:53
Duplicate of #894

**Closed by mattr555** 2017-11-30 01:53 UTC
