### ISSUE TITLE
Irrelevant/badly parsed result for iOS devices

### ISSUE THREAD

**Issue by yegg** [duckduckgo/zeroclickinfo-fathead#135] opened 2015-06-18 13:48 UTC
https://duckduckgo.com/?q=iOS+devices&ia=about

http://duck.co/ia/view/ios

**Comment by javathunderman** [comment] 2015-06-23 14:18
Duplicate of #134

**Comment by moollaza** [comment] 2015-06-23 17:43
Closing as it's a duplicate.

**Closed by moollaza** 2015-06-23 17:43 UTC
