### ISSUE TITLE
Numpy: Unable to fetch docs.

### ISSUE THREAD

**Issue by souravbadami** [duckduckgo/zeroclickinfo-fathead#696] opened 2017-01-18 18:20 UTC
### Description

Fetching _Numpy_ docs returns 404.

## Steps to recreate

Try to execute **fetch.sh** from numpy parser.

## People to notify

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/numpy

**Comment by pjhampton** [comment] 2017-01-18 18:50
Hey @souravbadami,

This is currently being addressed here: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/688

Hopefully we can get it merged soon.

**Closed by pjhampton** 2017-01-18 18:50 UTC

**Comment by moollaza** [comment] 2017-01-25 22:57
@pjhampton this is actually unrelated to #688 -- that issue is about the output.txt containing unescaped unicode.

@souravbadami can you provide more info? What errors are you seeing? Any ideas on the cause or fix?

**Comment by moollaza** [comment] 2017-01-25 22:59
@souravbadami I just ran the script on current master of the repo and everything seems to work just fine. I'm not seeing any errors...

Please confirm you're not mistaken. Which python are you using?

**Comment by pjhampton** [comment] 2017-01-26 10:25
@moollaza are you sure? He says he couldn't fetch the docs using the fetch.sh. In #688 they fixed the [redundant link here](https://github.com/PuneetGupta123/zeroclickinfo-fathead/commit/1d473700b8775886c86adfff999b2fac90cd3e90#diff-841056973cd7299649f49bd14f377416) along side the output.txt issue. The reason why it works now is because it got merged. The original link which @souravbadami is referring to [throws a 404](https://docs.scipy.org/doc/numpy/numpy-html-1.11.0.zip).

**Comment by moollaza** [comment] 2017-01-26 16:29
@pjhampton aah, thanks for explaining! Now I understand. Glad to know the problem is solved then 👍
