### ISSUE TITLE
MDN JS: add categories

### ISSUE THREAD

**Issue by MariagraziaAlastra** [duckduckgo/zeroclickinfo-fathead#528] opened 2016-11-03 19:25 UTC
### Description
Add categories, like in [jQuery](https://duck.co/ia/view/jquery): the sections names in MDN would make good categories (e.g. Classes, Errors, Functions...)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdnjs

**Comment by divyanshu-rawat** [comment] 2016-11-25 15:21
Hey I'm new, but I'd like to contribute to your organization, can someone please guide me along ? I am still not been able to understand what the issue is .

**Comment by bfmags** [comment] 2016-11-25 17:25
Hey @divyanshu-rawat, thank you for wanting to contribute! :) 

Basically it's separating the articles into categories based on the [MDN Reference structure](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference).

The categories  are `Global Objects`, `Errors`, `Functions`, `Classes`, `Statements`, `Operators` and we're also using `API` (take a look at the download patterns in [fetch.sh](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdnjs/fetch.sh) script):

- `mdn js global objects`
- `mdn js errors`
- `mdn js functions`
- `mdn js classes`
- `mdn js statements`
- `mdn js operators`

To accomplish this, we need to add the relevant category to each article (as covered in the documentation page for [Fathead IA](https://docs.duckduckhack.com/resources/fathead-overview.html))

So, for instance, for the article `Date.prototype.setDate`, we'll add the category `mdn js  global objects`

`Date.prototype.setDate	A			mdn js  global objects							<section class="prog__container"><p>The setDate() method sets the day of the Date object relative to the beginning of the currently set month.</p><pre><code>Date.prototype.setDate (date)</code></pre></section>	https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setDate`

When you've finishing categorising all articles, a search for `mdn js global objects` will return a card list, something like the result for [`css pseudo elements`](https://duckduckgo.com/c/css_pseudo_elements?ia=list).

This will get you started, reach out if you need more help!
______
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions/get involved with the community
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

**Comment by BillyBarbaro** [comment] 2017-03-07 02:11
@pjhampton If this isn't too urgent, I could probably get to it in the next week or so.

**Comment by pjhampton** [comment] 2017-03-07 10:27
Closing as this is no longer high priority 👍  
Same as last issue @BillyBarbaro 😄

**Closed by pjhampton** 2017-03-07 10:27 UTC
Labels: Mission: Programming, Skill: Python, Status: Work In Progress, Topic: JavaScript
